#cloud-config
debug:
   verbose: true

cloud_final_modules:
- [users-groups,always]

users:
  - default
  - name: codebuild
    ssh_authorized_keys: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM5yrzesUuZMVpOlcheURn2Zvn4BuyXAyl1qxNOrLvQL
    sudo: ALL=(ALL) NOPASSWD:ALL

# The Al2 verion at https://cdn.amazonlinux.com/os-images/2.0.20230628.0/
# ships with the 4.x kernel, an update and reboot is required.
# https://repost.aws/knowledge-center/amazon-linux-2-kernel-upgrade